DROP TABLE IF EXISTS TRANSACTIONS;
DROP TABLE IF EXISTS AGREEMENTS;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS CARDS;
DROP TABLE IF EXISTS ACCOUNTS;
DROP TABLE IF EXISTS CLIENTS;
DROP TABLE IF EXISTS MANAGERS;